Traceback (most recent call last):
  File "/home/uncoder/sm6-books/computer-sim-labs/.venv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/uncoder/sm6-books/computer-sim-labs/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/uncoder/sm6-books/computer-sim-labs/.venv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/uncoder/sm6-books/computer-sim-labs/.venv/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/uncoder/sm6-books/computer-sim-labs/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/uncoder/sm6-books/computer-sim-labs/.venv/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# –°–æ–∑–¥–∞—ë–º "–ø—É—Å—Ç–æ–π" –ö–ê
ca = create_ca(w, h)
# –ó–∞–¥–∞—ë–º –Ω–∞—á–∞–ª—å–Ω–æ–µ —Å–æ—Å—Ç–æ—è–Ω–∏–µ –ö–ê
init_state(ca, eta)
# –¢–∞–∫–∂–µ —Å—Ç–æ–∏—Ç –∑–∞–ø–æ–º–Ω–∏—Ç—å –∏—Å—Ö–æ–¥–Ω–æ–µ —Å–æ—Å—Ç–æ—è–Ω–∏–µ
initial_ca = np.copy(ca)
# –°–∏–º—É–ª–∏—Ä—É–µ–º.
# –í –¥–∞–Ω–Ω–æ–º —Å–ª—É—á–∞–µ —Ä–∞—Å—Å–º–∞—Ç—Ä–∏–≤–∞–µ–º "+"-–æ–∫—Ä–µ—Å—Ç–Ω–æ—Å—Ç—å
st = simulate(ca, NeighborhoodType.CROSS)
# –û–±—Ä–∞–±–∞—Ç—ã–≤–∞–µ–º —Ä–µ–∑—É–ª—å—Ç–∞—Ç—ã, —Å—Ç—Ä–æ–∏–º –≥—Ä–∞—Ñ–∏–∫–∏ –∏ –ø—Ä.
...
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[14], line 4[0m
[1;32m      2[0m ca [38;5;241m=[39m create_ca(w, h)
[1;32m      3[0m [38;5;66;03m# –ó–∞–¥–∞—ë–º –Ω–∞—á–∞–ª—å–Ω–æ–µ —Å–æ—Å—Ç–æ—è–Ω–∏–µ –ö–ê[39;00m
[0;32m----> 4[0m [43minit_state[49m[43m([49m[43mca[49m[43m,[49m[43m [49m[43meta[49m[43m)[49m
[1;32m      5[0m [38;5;66;03m# –¢–∞–∫–∂–µ —Å—Ç–æ–∏—Ç –∑–∞–ø–æ–º–Ω–∏—Ç—å –∏—Å—Ö–æ–¥–Ω–æ–µ —Å–æ—Å—Ç–æ—è–Ω–∏–µ[39;00m
[1;32m      6[0m initial_ca [38;5;241m=[39m np[38;5;241m.[39mcopy(ca)

[0;31mTypeError[0m: init_state() missing 1 required positional argument: 'f'

